# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins
import spanish_complexity.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('task1decision', spanish_complexity.fields.LotteryField(choices=[(False, 'No pagar el costo'), (True, 'Pagar el costo')], verbose_name='\n¿Quiere pagar el costo en la Tarea 1? El costo es 150 ECUs ECUs, Si paga, las probabilidades de Éxito en la \ntarea son de 5 de 10.')),
                ('task2decision', spanish_complexity.fields.LotteryField(choices=[(False, 'No pagar el costo'), (True, 'Pagar el costo')], verbose_name='\n¿Quiere pagar el costo en la Tarea 2? El costo es 150 ECUs ECUs, Si paga, las probabilidades de Éxito en la \ntarea son de 5 de 10.')),
                ('task1outcome', otree.db.models.BooleanField(choices=[(True, 'Éxito'), (False, 'Fracaso')])),
                ('task2outcome', otree.db.models.BooleanField(choices=[(True, 'Éxito'), (False, 'Fracaso')])),
                ('task1guess', spanish_complexity.fields.LotteryField(choices=[(False, 'No pagar el costo'), (True, 'Pagar el costo')], verbose_name='Player 1 will pay the cost on Task 1')),
                ('task2guess', spanish_complexity.fields.LotteryField(choices=[(False, 'No pagar el costo'), (True, 'Pagar el costo')], verbose_name='Player 1 will pay the cost on Task 2')),
                ('retaining', otree.db.models.IntegerField(choices=[(0, 'NUNCA recompensar al Jugador 1'), (1, 'Recompensar al Jugador si y sólo sí el Resultado es Éxito en AMBAS Tareas'), (2, 'Recompensar al jugador 1 si y sólo sí el Resultado es Éxito en al menos una Tarea  (eso es,  O en la Tarea 1, O en la Tarea 2, O en AMBAS Tareas  1 y 2)'), (3, 'Recompensar al Jugador 1 si y sólo sí el Resultado es Éxito en sólo una Tarea (Tarea 1 O Tarea 2)'), (4, 'SIEMPRE Recompensar al Jugador 1')], null=True, verbose_name='Elija una Regla para Recompensar o No Recompensar al Jugador 1')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spanish_complexity_group', to='otree.Session')),
            ],
            options={
                'db_table': 'spanish_complexity_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('temp_payoff', otree.db.models.CurrencyField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spanish_complexity.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spanish_complexity_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spanish_complexity_player', to='otree.Session')),
            ],
            options={
                'db_table': 'spanish_complexity_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spanish_complexity_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'spanish_complexity_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spanish_complexity.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spanish_complexity.Subsession'),
        ),
    ]
