# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 03:58
from __future__ import unicode_literals

from django.db import migrations
import spanish_complexity.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spanish_complexity', '0002_auto_20180604_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='task1decision',
            field=spanish_complexity.fields.LotteryField(choices=[(False, 'No pagar el costo'), (True, 'Pagar el costo')], verbose_name='\n¿Quiere pagar el costo en la Tarea 1? El costo es 150 ECUs ECUs, Si paga, las probabilidades de Éxito en la \ntarea son de 5 de 10.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='task2decision',
            field=spanish_complexity.fields.LotteryField(choices=[(False, 'No pagar el costo'), (True, 'Pagar el costo')], verbose_name='\n¿Quiere pagar el costo en la Tarea 2? El costo es 150 ECUs ECUs, Si paga, las probabilidades de Éxito en la \ntarea son de 5 de 10.'),
        ),
    ]
